version: "3.3"
services:
  gen_electricity_bot:
    build: .
    restart: unless-stopped
    image: gen_electricity_bot
    container_name: GenElectricityBot
    env_file: ./.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
